version: "3.1"

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: s1n431stl5
      MYSQL_DATABASE: reddit_clone_NeoPing
    ports:
      - "3306:3306"
